### ISSUE TITLE
Onedrived won't start

### ISSUE THREAD

**Issue by FlavioMiglio** [xybu/onedrived-dev#113]
Hi, I just installed and configured Onedrived on my Xubuntu machine. when I try to open it by doing 'onedrived start' it gives back this text: https://pastebin.com/MtSSwPL4 and it doesn't work. Any ideas? thanks in advance

**Comment by derrix060** [comment]
please try to install python-dev on your machine: `apt install python-dev` and also update psutil: `pip3 install -U psutil`

**Comment by derrix060** [comment]
Please make sure you have followed all the steps from the installation, including the [pre-requisites](https://github.com/xybu/onedrived-dev#pre-requisites)

**Comment by FlavioMiglio** [comment]
It's all correct; I just tried to reinstall and now it gives me 
onedrived start
Starting onedrived ... FAILED
ERROR: Child exited immediately with exit code 127

**Comment by derrix060** [comment]
try to run again with `--debug`

**Comment by FlavioMiglio** [comment]
There's my output. Thank you for the help
https://pastebin.com/fcZPj0N5
