### ISSUE TITLE
Child exited with code 127

### ISSUE THREAD

**Issue by KennethWilke** [xybu/onedrived-dev#15]
Hello!

I pulled the current master branch and configured an account. The main deamon is exiting with the folllowing:

```
$ python3 -m onedrived.od_main start
Starting od_main.py ... FAILED
ERROR: Child exited immediately with exit code 127
```

**Comment by xybu** [comment]
There are actually a few more steps to configure the problem but I haven't updated the documentation (e.g., `onedrived-pref drive --help`, and to download and install `ngrok`)... If you don’t have log file path set properly (undocumented…), use “--debug” to not run in daemon mode and print verbose debug log.

**Comment by schnuffmax** [comment]
Hey there :)

Having actual the same problem. I've download ngrok already but now getting the following problem:

File "/home/max/.local/lib/python3.5/site-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_webhooks/ngrok_server.py", line 68, in _start_ngrok_process
    raise RuntimeError('Ngrok process exited early.')
RuntimeError: Ngrok process exited early.

Maybe you know what to do - if you have time ;)

Thanks

**Comment by xybu** [comment]
@schnuffmax Put `ngrok` binary in your `PATH`.

**Comment by vk5ztv** [comment]
I have the same problem when trying to run as a daemon, but it runs fine in debug mode.

**Comment by xybu** [comment]
@vk5ztv  Problem confirmed.

**Comment by xybu** [comment]
Made some stupid mistake when introducing config guard. The commit 6020bf437c41aaea45b2b2427203c6507ded3c8a would fix the problem.

**Comment by vk5ztv** [comment]
Confirmed that commit 6020bf4 fixes the problem when running directly from the source directory as python3 -m onedrived.od_main start. There seems to be another issue when attempting to stop the daemon but I'll log that as a separate issue.

**Comment by xtien** [comment]
it is "~/.ngrok

**Comment by derrix060** [comment]
Remember that you can always set a specific path for ngrok: `NGROK=/path/to/ngrok onedrived start`

**Comment by gr00vy** [comment]
Check the log file location in ~/.config/onedrived/onedrived_config_v2.json.
Mine was pointing to /var/log/onedrived folder which wasn't created and could be created only by sudoers.
So simple solution was:
sudo mkdir /var/log/onedrived
sudo chmod 777 /var/log/onedrived
