### ISSUE TITLE
Missing .config/onedrived/onedrived_config_v2.json file

### ISSUE THREAD

**Issue by thnuder** [xybu/onedrived-dev#18]
fresh install missing this file on the home directory in fedora 25
getting this error when running onedrived-pref

WARNING:root:Failed to load config file: [Errno 2] No such file or directory: '/home/user/.config/onedrived/onedrived_config_v2.json'. Use default.

can not use onedrived-pref as no command accepted as per the readme example in the main page

**Comment by alikhil** [comment]
I have the same problem #6

**Comment by xybu** [comment]
What do you mean by "no command accepted"? Can you paste some output here?

**Comment by dandarie** [comment]
I also have the same problem.

Here's the output:
```
$ onedrived-pref account add
WARNING:root:Failed to load config file: [Errno 2] No such file or directory:
'/home/dan/.config/onedrived/onedrived_config_v2.json'. Use default.
Usage: onedrived-pref [OPTIONS] COMMAND [ARGS]...

Error: No such command "account"
```

**Comment by xybu** [comment]
I guess that's related to how `onedrived.od_pref` is executed in the shortcut. Maybe the setup script didn't create the shortcut properly (e.g., it runs `main()` directly but there's some decorations outside `main()`).

**Comment by xybu** [comment]
The commit `96f5df7c619ac8c0bce938a238bf415e512c2a46` should fix the problem, but seriously, this program isn't ready yet. If you insist on using it, at least install `ngrok` (https://ngrok.com/download) under your `PATH`.
