### ISSUE TITLE
Did not find ngrok executable "ngrok"

### ISSUE THREAD

**Issue by charon120** [xybu/onedrived-dev#26]
INFO: MainThread: Sweeping onedrived temporary files from local repositories.
CRITICAL: MainThread: Error initializing webhook: Did not find ngrok executable "ngrok".
INFO: MainThread: Shutting down. Code: Exiting with message: None.
INFO: Worker-1: Stopped.
INFO: Worker-0: Stopped.
INFO: MainThread: Shut down complete.

**Comment by charon120** [comment]
ubuntu系统如何安装？

**Comment by xybu** [comment]
在 https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip 下载ngrok的可执行文件，然后丢进/usr/local/bin就行

或者如果想手工设定`ngrok`的路径，就需要运行onedrived之前设置`NGROK`环境变量，比如，如果你把`ngrok`放在`~/.bin/`下面，但是`~/.bin/`不在`PATH`里，则运行`onedrived`需要用比如下面这样的命令：

```
NGROK=~/.bin/ngrok onedrived start --debug
```

**Comment by charon120** [comment]
谢谢，解决了。
