### ISSUE TITLE
Exclude pathes

### ISSUE THREAD

**Issue by Graf17** [xybu/onedrived-dev#28]
OK, I have a local folder called "MP3" with thousand of subfolders and files in it. This folder I don't want to be synced to my onedrive. Is there a way to exclude it completely? I haven't found an option in the  "ignore_v2.txt"-file.

Thanks in advance!

**Comment by hoo29** [comment]
You can specify it's full path, relative to the root of your OneDrive folder, and stick it in the ignore file. If the path has spaces in be sure to escape them with \.

**Comment by Graf17** [comment]
OK, thank you very much! That seems to work.
