### ISSUE TITLE
Could you add how the readme how to exclude remote directories (selective sync)?

### ISSUE THREAD

**Issue by softwareuser99** [xybu/onedrived-dev#34]
Would it be sufficient to add the remote folder names I want to exclude in the ignore_v2.txt? Could you maybe shed some light on that?

So for example, I have a ONEDRIVE main folder called PICS. How can I prevent this from syncing?

# Created by https://www.gitignore.io/api/linux,windows,macos

Thanks for the awesome little program!

**Comment by jul13579** [comment]
As of what I know, the file follows the gitignore-rules, which can be found here:
[https://git-scm.com/docs/gitignore](url)

**Comment by softwareuser99** [comment]
Cheers, looks like that's indeed the case, I'll play with it and if it doesn't work, I'll revert. For now, topic closed, thanks!
