### ISSUE TITLE
Error to add an account: Failed to save account: 'emails'.

### ISSUE THREAD

**Issue by derrix060** [xybu/onedrived-dev#40]
When I was adding an account, this message was showed:

_Successfully authorized onedrived._
_Successfully added account for Mário Aprá (mario_surfing@hotmail.com)!_
_All OneDrive accounts associated with user "mario":_
**Failed to save account: 'emails'.**

And when i type `onedrived-pref account list` this showed:
_Traceback (most recent call last):_
  _File "/usr/local/bin/onedrived-pref", line 11, in <module>_
    _load_entry_point('onedrived', 'console_scripts', 'onedrived-pref')()_
  _File "/home/mario/.local/lib/python3.5/site-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_pref.py", line 83, in main_
    _main_cmd()_
  _File "/home/mario/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)_
  _File "/home/mario/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)_
  _File "/home/mario/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))_
  _File "/home/mario/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))_
  _File "/home/mario/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)_
  _File "/home/mario/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)_
  _File "/home/mario/.local/lib/python3.5/site-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_pref.py", line 149, in list_accounts
    print_all_accounts(context)_
  _File "/home/mario/.local/lib/python3.5/site-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_pref.py", line 50, in print_all_accounts
    all_accounts.append((str(i), account_id, account.account_name, account.account_email))_
  _File "/home/mario/.local/lib/python3.5/site-packages/onedrived-2.0.0-py3.5.egg/onedrived/od_models/account_profile.py", line 26, in account_email
    r**eturn self.data['emails']['account']**
KeyError: 'emails'_

**Comment by xybu** [comment]
Might you share whatever the file `~/.config/onedrived/onedrived_config_v2.json` contains with me? It seems the API returned something of unexpected format and I need to know this to adapt the code to this format.

Another way to debug this is to add a line `print(data)` above this place: https://github.com/xybu/onedrived-dev/blob/master/onedrived/od_auth.py#L82 to see what the Live API returns.
