### ISSUE TITLE
Error on running onedrived-pref

### ISSUE THREAD

**Issue by alikhil** [xybu/onedrived-dev#6]
I have just installed onedrived manually and have an error on running `onedrive-pref`

```shel
$ onedrived-pref 
ERROR:root:Failed to load config file: [Errno 2] No such file or directory: '/home/alik/.config/onedrived/onedrived_config_v2.json'. Use default.
Usage: onedrived-pref [OPTIONS] COMMAND [ARGS]...

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.
```

**Comment by xybu** [comment]
The output said that the program created the default config file when you ran it for the first time, and didn't do anything because you didn't specify what to do in the command.

**Comment by alikhil** [comment]
@xybu tell me which commands could be entered, please?
