### ISSUE TITLE
i have no idea how to make onedrive side ignore

### ISSUE THREAD

**Issue by survivor303** [xybu/onedrived-dev#65]
When i sync, i dont wantsync etc my music directory to my computer from onedrive.
How i can do that?

**Comment by derrix060** [comment]
As written on [#28](https://github.com/xybu/onedrived-dev/issues/28), try to add the path on "ignore_v2.txt"-file to ignore it. I know that your problem is the opposite, but I think it will work.

**Comment by Wouter-VDP** [comment]
I can confirm that this works in both sides
