### ISSUE TITLE
Fail to install at an arm device

### ISSUE THREAD

**Issue by lcgogo** [xybu/onedrived-dev#79]
Hi, i met an issue when install onedrived-dev

root@WDMyCloud:/tmp# pip3 install git+https://github.com/xybu/onedrived-dev.git

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.4m -c c/_cffi_backend.c -o build/temp.linux-armv7l-3.4/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gu_7af4n/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4ddm2v29-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-gu_7af4n/cffi/

My python3 is 3.4.2 . is it related?
root@WDMyCloud:/tmp# python3 --version
Python 3.4.2

**Comment by xybu** [comment]
By any chance, try this?

https://stackoverflow.com/questions/12982486/glib-compile-error-ffi-h-but-libffi-is-installed

**Comment by lcgogo** [comment]
Are you working in Vestas?

**Comment by lcgogo** [comment]
Thanks, fixed. But one more error

`    subprocess.CalledProcessError: Command '['/tmp/pip-build-c7sexry7/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-build-c7sexry7/dbus-python/build/temp.linux-armv7l-3.4/prefix']' returned non-zero exit status 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c7sexry7/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ttwkstzx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-c7sexry7/dbus-python/
`

**Comment by lcgogo** [comment]
I use the #58 comments and now installed ok

 apt-get install python3 build-essential python3-dev libssl-dev inotify-tools python3-dbus libffi-dev libdbus-glib-1-dev -y
