### ISSUE TITLE
why i need to set up kde wallet?

### ISSUE THREAD

**Issue by 243750496** [xybu/onedrived-dev#85]
![kde wallet](https://user-images.githubusercontent.com/6311930/34111379-85bb3676-e444-11e7-9ad2-8fb1c0958af7.png)
it seems if i don't set it , the onedrived will not start ,any solutions?

**Comment by derrix060** [comment]
You need to setup some key ring to encrypt your password! Because of your os version, the default is the KDE Wallet.

**Comment by 243750496** [comment]
Thank you so much!

**Comment by derrix060** [comment]
@xybu close it?

**Comment by xybu** [comment]
Thanks for helping me answer questions :)
