### ISSUE TITLE
Files under deep folder structures are not synced

### ISSUE THREAD

**Issue by zigchg** [xybu/onedrived-dev#89]
I have files under 3 levels of folders that are not synced. More specifically, it is like:
/Onedrive/level1/level2/level3/
Everything under level3 is not synced.

**Comment by zigchg** [comment]
I closed this issue. The syncing is slow, but eventually all files are synced.

**Comment by Darksoulsong** [comment]
I have this very same issue, and my files are never synced. Onedrived creates the folders, but they are empty.
