### ISSUE TITLE
You suggest ngrok, but ngrok is not open source. Alternative?

### ISSUE THREAD

**Issue by passboltUser** [xybu/onedrived-dev#90]
In your README you are suggesting ngrok, but it looks like it's not open source, at least not since version 2.x.Why not an open source alternative?

**Comment by derrix060** [comment]
@passboltUser I can say for myself (in my [fork](https://github.com/derrix060/onedriveClient)) I haven't changed it because I will need to refactor a lot of code. You can still use the 2.x version, can't you?

**Comment by passboltUser** [comment]
@derrix060 Yes, I can/am already using v2. But you have an alternative to NGROK in mind/found one? But I have to say now: If one is alrady using OneDrive, any open source alternative doesn't make sence because OneDrive/Microsoft is not an open source company. So I'm closing my issue.
