### ISSUE TITLE
is it really working?

### ISSUE THREAD

**Issue by Unixware** [xybu/onedrived-dev#92]
Seems it syncs some changes then when I delete some files I only get;

[2018-02-12 22:11:19,708] INFO: Worker-1: Record for item XXXXX (filename) is dead. Delete it it.

I restarted the program, still no changes online, looks like the deletions must be performed 'manually' ?

**Comment by derrix060** [comment]
It should be automatically. Can you provide more detail? I've tested here on my computer (with my [fork](https://github.com/derrix060/onedriveClient)) and it's deleting from the cloud when I delete in my directory.

**Comment by Unixware** [comment]
tried your fork and works like a charm! many thanx!
