### ISSUE TITLE
Best way to autostart onedrived-dev

### ISSUE THREAD

**Issue by rickstaa** [xybu/onedrived-dev#96]
Dear Developer,

What is the best way to start the "onedrived" app during start-up. I now added the command to the "Startup Applications Preferences" but I was wondering If it is not smarter to add the command to the default startup bash script? What way would you suggest?

Thanks a lot in advance,
Greetings,
Rick,

**Comment by derrix060** [comment]
I don't think that this is an issue specific to this project.

Anyway, If your idea is to restrict this to only your user (what makes sense), this is the best place to put it. If you want to run it, no matter what user, then you will need to double check your files permission and add it on `/etc/rc.local` before the `exit 0`.

**Comment by rickstaa** [comment]
Ah, thanks a lot for your response :).
