### ISSUE TITLE
Ondrived-dev does not sync all my files (Some folders stay empty)

### ISSUE THREAD

**Issue by rickstaa** [xybu/onedrived-dev#97]
Dear Developers,

I really love your app and at first, it seemed to work but after waiting for 3 days the app hasn't synced all my folders while the status check says the daemon is still asleep. I think this has something to do with ngrok giving me this error message:

![error](https://user-images.githubusercontent.com/17570430/39472220-43a1fb4a-4d48-11e8-8168-ac21e69792a4.png)

However when I try to click on the request link I get the following error:

![error2](https://user-images.githubusercontent.com/17570430/39472270-90f21bfa-4d48-11e8-96f7-a7bb8faa60c3.png)

### Other things I tried
I also tried removing the deleting the items_*.sqlite3 file in ~/.config/onedrived. But sofar It doens't seem to solve the issue. I need to do some testing to be sure.

**System info**
Laptop: HP Studio G3
OS (Kernel): Linux ubuntu Bionic beaver (18.04)
onedrived auto start command: onedrived start

** Status log **
[Download log file:](https://we.tl/1oar25YPBe)

**Comment by rickstaa** [comment]
It seems to be working now don't know what changed.

**Comment by derrix060** [comment]
@xybu close it?

**Comment by rickstaa** [comment]
@xybu  Yea thanks it is fixed for now :)
